### ISSUE TITLE
[Suggestion] Add the latest firmware

### ISSUE THREAD

**Issue by 1alessandro1** [4IceG/EM12-G#3]
Before it is taken down, here is the download link of the newest EM12-G firmware provided by Quectel

https://quectel123-my.sharepoint.cn/:u:/g/personal/ae-fae_dom_quectel_com_cn/EcnAfJi7MFtGvi4zScHMsPEBsmczsKxNwo3QLbrN_VGz8g?e=4%3A2df09c60779c4b98b2d512fb05a31dce

If the link becomes unavailable, let me know, I will attach a new mega link

**Comment by 4IceG** [comment]
Hi @1alessandro1
OK, thanks. I will add a new version this afternoon/evening.
